config/routes.rb
require 'routes/exceptions_app_constraint'
require 'routes/client_app_constraint'
require 'routes/counsel_app_constraint'
require 'routes/signer_app_constraint'

Doxly::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  concern :account_settings do
    get :my_profile, to: 'account_settings#my_profile'
    put :my_profile, to: 'account_settings#my_profile_save'
    get :integrations, to: 'account_settings#integrations'
    get :change_email, to: 'account_settings#change_email'
    post :change_email, to: 'account_settings#change_email_save'
    put :reconfirm_change_email, to: 'account_settings#reconfirm_change_email'
    put :cancel_change_email, to: 'account_settings#cancel_change_email'
    get :change_password, to: 'account_settings#change_password'
    put :change_password, to: 'account_settings#change_password_save'
    get :two_factor_authentication_settings, to: 'account_settings#two_factor_authentication_settings'
  end

  concern :entity_settings do
    get :entity_profile, to: 'entity_settings#entity_profile'
    post :entity_profile, to: 'entity_settings#entity_profile_save'
  end

  concern :starring do
    member do
      get :star
      get :unstar
    end
  end

  concern :documentable do
    get :mark_as_final
    get :undo_final
    get :view_document
  end

  concern :collection_refresh_list do
    get :refresh_list, :on => :collection
  end

  concern :working_group_intro do
    get :completed_working_group_intro, :on => :collection
    put :completed_working_group_intro, :on => :collection, to: 'roles#update_completed_working_group_intro'
  end

  concern :view_and_download do
    get :view, on: :member
    get :download, on: :member
  end

  def download_helpers(scope)
    get "/uploads/deals/:id/closing_books/:id/attachment/:filename",  :controller => "closing_books",  :action => "download_attachment", :constraints => {:filename => /.+(\/.+)*/ }, :as => "download_closing_book_attachment_as_#{scope}"
    get "/uploads/deals/:id/closing_books/:id/logo/:filename",  :controller => "closing_books",  :action => "download_closing_book_logo", :constraints => {:filename => /.+(\/.+)*/ }, :as => "download_closing_book_client_logo_as_#{scope}"
  end

  # For exception handling
  constraints ExceptionsAppConstraint do
    get '/404' => 'errors#render_not_found'
    get '/500' => 'errors#render_internal_server_error'
    get '*path' => 'errors#render_not_found'
  end

  get :register, to: 'registration#edit'
  put :register, to: 'registration#update'
  get :login_tokens, to: 'login_tokens#show'

  # For receiving the notifications from esignature providers
  post 'esignature_notifications' => 'esignature_notifications#index'

  match 'sso/adfs/federation_metadata(*path)' => 'sso#adfs_metadata', :via => :get

  constraints :subdomain => /^(?!api)(\w+)/ do
    scope :module => 'app' do
      devise_for :users, :path => '', :module => 'app/devise', :skip => [:passwords]
      devise_scope :user do
        post :forgot_password, :to => 'devise/passwords#create', :as => :user_password
        get :forgot_password, :to => 'devise/passwords#new', :as => :new_user_password
        get 'forgot_password/edit', :to => 'devise/passwords#edit', :as => :edit_user_password
        put :forgot_password, :to => 'devise/passwords#update'
        post 'auth/:saml/callback' => 'devise/omniauth_callbacks#success'
        get 'auth/:saml/setup' => 'devise/omniauth_callbacks#setup'

        unauthenticated do
          root to: 'devise/sessions#new'
        end
      end

      get :time_zone, to: 'time_zone#set'

      get :entity_switch, to: 'entity_switch#index'
      post :entity_switch, to: 'entity_switch#switch'

      get :refresh_api_auth, to: 'refresh_api_authentication#index'

      get "/uploads/user/:id/avatar",  :controller => "users",  :action => "show_avatar", :as => "show_user_avatar"

      resources :zendesk_sessions, only: [:index, :new]

      constraints CounselAppConstraint do
        scope :module => 'counsel' do
          get :docusign_settings, to: 'entity_settings#docusign_settings'
          post :docusign_settings, to: 'entity_settings#docusign_settings_save'
          get :licenses, to: 'entity_settings#licenses'
          concerns :account_settings, :entity_settings
          resources :net_documents_user_credentials, only: [] do
            get :authorize, on: :collection
          end
          resources :see_unity_imanage_user_credentials, only: [:create, :update]
          resources :imanage10_user_credentials, only: [:create, :update]
          resources :deals, :except => [:destroy, :show], :concerns => :collection_refresh_list do
            put :set_critical_errors_as_read
            resources :attachments do
              resources :versions, :concerns => :view_and_download
            end
            get :executed_versions
            get :export_tracker
            resources :closing_books do
              get :download_closing_book, :on => :member
              get :upload_cover_page, :on => :collection
              post :uploaded_cover_page, :on => :collection
              get :view_cover_page, :on => :collection
              get :show_cover_page, :on => :collection
              delete :remove_cover_page, :on => :collection
            end
            resources :questionnaires, :except => :destroy do
              post :save_responses, :on => :collection
            end
            get :voting_threshold
            resources :signature_groups do
              resources :block_collections, only: [] do
                resources :signature_entities, only: [] do
                  member do
                    get :include
                    get :exclude
                  end
                end
                resources :signing_capacities do
                  member do
                    get :include
                    get :exclude
                  end
                end
              end
              get  :import_from_working_group
              post :imported_from_working_group
            end
            resources :signature_pages, :concerns => :view_and_download do
              get :upload_custom_signature_page
              post :uploaded_custom_signature_page
              get :choose_from_document
              get :document_page_thumbnail
              get :view_document_page
              post :process_choose_from_document
              get :remove_custom_signature_page
              get :show_custom_signature_page
              get :edit_custom_signature_page
              get :signature_groups, :on => :collection
              get :show_signature_page, :on => :collection
              get :show_signature_page_entity, :on => :collection
              get :view_signature_page, :on => :collection
              get :download_thumbnail_sprite, on: :member
              get :download_custom_page_thumbnail, on: :member
              resources :signature_tabs, only: [:new, :create] do
                get :remove
              end
            end
            resources :signature_packets, :concerns => :view_and_download do
              get :display_signature_packet
              delete :void_signature_packet
              collection do
                get    :send_packets_confirm
                post   :send_packets
                get    :send_packet_wizard
                post   :send_packet
                get    :upload_manual_signatures
                post   :uploaded_manual_signatures
                get    :manage_signature_packets
                get    :view_signature_pages
                get    :send_reminder
                post   :remind_signer
                get    :set_default_signature_type_confirm
                get    :set_default_signature_type
                get    :cancel_set_default_signature_type
              end
            end
            resources :roles, concerns: :working_group_intro
            concerns :starring
            get :select_client, :on => :collection
            post :select_client_confirm, :on => :collection
            get :add_address, :on => :collection
            get :signature_page_settings

            resources :unmatched_signature_uploads do
              resources :unmatched_signature_upload_pages, concerns: :view_and_download
            end

            member do
              get :archive
              get :unarchive
              get :close
              get :reopen
            end

            resources :deal_entities, only: [:index, :new, :create, :destroy] do
              get :add_address, :on => :collection
              resources :deal_organization_users, except: [:index, :edit, :update, :show] do
                get :prepare_deal_invitation
                post :send_deal_invitation
              end
            end
            resources :deal_individual_users, only: [:index, :new, :create, :destroy] do
              get :prepare_deal_invitation
              post :send_deal_invitation
            end
            resources :categories do
              resources :tree_elements do
                get :edit_signature_page_footer
                get :edit_signature_page_header
                put :set_signature_page_header, :on => :member
                put :set_signature_page_footer, :on => :member
                get :set_signature_type
                get :set_show_footer, :on => :member
                get :set_show_header, :on => :member
                get :set_show_address, :on => :member
                get :set_show_date_signed, :on => :member
                put :update_multiple_pages, :on => :member
                get :render_redline_pdf
                resources :tree_element_signature_groups do
                  get :set_show_group_name, :on => :member
                end
                resources :attachments do
                  resources :versions, :concerns => :view_and_download do
                    get :sync_thumbnails

app/models/questionnaire.rb
class Questionnaire < ActiveRecord::Base
  belongs_to :deal_type
  has_many   :questions,  :dependent => :destroy

  validates_presence_of :deal_type_id
end

app/controllers/app/counsel/account_settings_controller.rb
class App::Counsel::AccountSettingsController < App::ApplicationController
  include Controllers::AccountSettings

  def integrations
    check_create(:entity_level_dms_integration)
  end
end

app/controllers/app/counsel/attachments_controller.rb
class App::Counsel::AttachmentsController < App::ApplicationController
  include Controllers::Attachments
end

app/controllers/app/counsel/categories_controller.rb
class App::Counsel::CategoriesController < App::ApplicationController
  include Controllers::Categories

  layout "deals"
end

app/controllers/app/counsel/closing_books_controller.rb
class App::Counsel::ClosingBooksController < App::ApplicationController
  include Controllers::ClosingBooks
  layout "deals"

  GENERATE_WAIT_TIME = 2.seconds

  def self.controller_path
    "app/counsel/deals/closing_books"
  end

  def new
    check_create(:closing_book)
    @closing_book = deal.closing_books.new
    File.delete(image_path) if File.exist?(image_path)
  end

  def create
    check_create(:closing_book)
    closing_book.attributes = closing_book_params
    closing_book.status     = 'not_started'
    cover_page              = document_path
    if closing_book.save
      # add a delay to the execution to account for saving the job id on the closing book
      job             = closing_book.delay(run_at: (Time.now + GENERATE_WAIT_TIME), queue: 'closing_books').generate! cover_page
      scheduled_job   = closing_book.build_scheduled_job(:job_id => job.id)
      scheduled_job.save
      flash[:success] = "The closing book has been created successfully"
      redirect_to deal_closing_books_path(deal)
    end
  end

  def destroy
    check_delete(:closing_book)
    closing_book.destroy
    flash[:success] = "The closing book has been deleted successfully"
    redirect_to deal_closing_books_path(deal)
  end

  def directory_path
    @directory_path ||= ClosingBook.folder_name(deal)
  end

  def image_path
    @image_path ||= directory_path + "/cover_page.jpg"
  end

  def document_path(file_extension='.pdf')
    directory_path + "/cover_page#{file_extension}"
  end

  def upload_cover_page
    check_create(:closing_book)
    closing_book
  end

  def uploaded_cover_page
    check_create(:closing_book)
    uploaded_file = params[:closing_book][:file]
    file_extension = File.extname(uploaded_file.original_filename.downcase) if uploaded_file.present?
    if uploaded_file.present? && ClosingBook::SUPPORTED_COVER_PAGE_FORMATS.include?(file_extension)
      save_cover_page_locally(file_extension, uploaded_file)
      if !File.exist?(document_path)
        closing_book.errors.add(:base, :cover_page_could_not_be_converted)
        render :upload_cover_page and return
      end
    else
      closing_book.errors.add(:base, :cover_page_upload_must_be_correct_extension)
      render :upload_cover_page and return
    end
    @uploaded_cover_page = File.exist?(image_path)
    render 'update_cover_page_view'
  end

  def save_cover_page_locally(file_extension, uploaded_file)
    # write the uploaded file to a local path
    File.open(document_path(file_extension), "wb") { |f| f.write(uploaded_file.read) } # download the file
    if file_extension != '.pdf'
      begin
        FileConvert.process_file_conversion(document_path(file_extension), document_path)
      ensure
        # delete the old .doc or .docx file
        File.delete(document_path(file_extension)) if File.exist?(document_path(file_extension))
      end
    end

    # save as image
    if File.exist?(document_path)
      ApplicationHelper.im_image_from_path(document_path) do |image|
        image.write(image_path)
      end
    end
  end

  def show_cover_page
    check_create(:closing_book)
    send_data(open(image_path){|f| f.read }, disposition: 'inline', type: 'image/jpeg')
  end

  def remove_cover_page
    check_create(:closing_book)
    closing_book
    File.delete(image_path) if File.exist?(image_path)
    render 'update_cover_page_view'
  end

  def view_cover_page
    check_create(:closing_book)
    closing_book
  end

  private

  def closing_book_params
    params.require(:closing_book).permit(:format, :logo, :logo_cache, :cover_text, :closing_book_sections_attributes => [:tree_element_id, :name, :position, :closing_book_documents_attributes => [:tree_element_id, :name, :tab_number]])
  end

end

app/controllers/app/counsel/deal_templates_controller.rb
class App::Counsel::DealTemplatesController < App::ApplicationController
  def index
    check_read(:deal_template)
    if category.is_closing? && deal.signature_packets.any?
      flash.now[:error] = "Cannot change template after signatures have been sent."
      render 'shared/blank' and return
    end
    @entity_templates = templates.where.not(entity_id: nil)
    @default_templates = templates.where(entity_id: nil)
  end

  def new
    check_create(:deal_template)
    category
    template
  end

  def create
    check_create(:deal_template)
    category

    # create new template
    template.assign_attributes(template_params)
    deal_type_template = template.deal_type_templates.new(:deal_type_id => deal.deal_type.id)

    # duplicate checklist
    if(category.is_diligence?)
      template.category = deal.diligence_category.dup_tree()
    else
      template.category = deal.closing_category.dup_tree()
    end

    # save
    if template.valid?
      if template.save
        flash.now[:success] = "Template exported successfully"
      else
        flash.now[:error] = "Unable to export template"
      end
    end
    templates
    redirect_to deal_category_path(deal, category)
  end

  def select
    check_create(:deal_template)
    templates
    category
    template
  end

  def apply
    check_update(:deal_template)

    # destroy existing checklist and duplicate template
    is_diligence_category = category.is_diligence?
    if(is_diligence_category)
      deal.diligence_category.destroy
      deal.diligence_category = template.category.dup_tree()
    else
      deal.closing_category.destroy
      deal.closing_category = template.category.dup_tree()
    end

    # save
    if deal.valid?
      if deal.save
        flash.now[:success] = "Template applied"
      else
        flash.now[:error] = "Unable to apply Template. Please try again"
      end
    end

    # update views
    deal.reload
    if(is_diligence_category)
      @category = deal.diligence_category
      @tree = deal.diligence_category.descendants.include_associations.as_tree
    else
      @category = deal.closing_category
      @tree = deal.closing_category.descendants.include_associations.as_tree
    end
    redirect_to deal_roles_path(deal)
  end

  private

  def deal
    @deal ||= current_entity_user.all_deals.find_by(:id => params[:deal_id])
  end

  def category
    @category ||= deal.categories.find(params[:category_id])
  end

  def template
    @template ||= params[:id].blank? ? current_entity.templates.new : current_entity.all_templates.find(params[:id])
  end

  def templates
    @templates = category.all_templates(current_entity.id, deal.deal_type_id)
  end

  def template_params
    params.require(:template).permit(:name)
  end
end

app/views/app/counsel/questionnaires/_questionnaire_form.html.erb
<%= form_for @deal, :url => save_responses_deal_questionnaires_path(@deal), :method => :post, :remote => true, :html => { :class => 'no-turboboost' } do |f| %>
  <%
    @questionnaire.questions.where(is_active: true).each do |question|
      has_dependency    = question.question_dependencies.any?
      dependent_id      = question.question_dependencies[0].dependent_question_id if has_dependency
      dependency_class  = has_dependency ? "has-dependency" : ""
      question_response = @question_responses.find_by :question_id => question.id
      answers           = question_response.present? ? question_response.question_answers : []
      # get the pre-populated answer
      answer_value      = questionniare_answer_value(@deal, question.value_key) if question.value_key.present?
  %>
    <div id="<%= question.id %>" class="form-group questionnaire-question <%= dependency_class %>" data-question-id="<%= dependent_id %>">
      <%= hidden_field_tag "deal[question_responses_attributes][][question_id]", question.id %>
      <%= f.fields_for @question_responses do |question_response_fields| %>
        <%= question_response_fields.fields_for :question_answers_attributes do |question_answer_fields| %>
          <label><%= question.field %></label>
          <% if question.type === 'DropdownQuestion' %>
            <%
              answer_value = answers.first&.option_id
            %>
            <%= question_answer_fields.select :option_id, options_for_select(question.question_options.order(:position).map{ |o| ["#{o.label}", o.id] }, [answer_value]), {:include_blank => 'Please Select...'}, { :name => "deal[question_responses_attributes][][question_answers_attributes][][option_id]", :class => 'selectpicker show-tick form-control' } %>
          <% elsif question.type === 'NumericQuestion' %>
            <%
              answer_value   = answers.first&.numeric_value
              currency       = question.unit_type === 'Currency'
              no_type        = question.unit_type === 'None'
              sign           = currency ? 'p' : 's'
              symbol         = currency ? '$ ' : '%'
              sign_placement = no_type ? '' : sign
              sign_type      = no_type ? '' : symbol
            %>
            <%= question_answer_fields.text_field :numeric_value, :value => answer_value, :class => "form-control", :name => "deal[question_responses_attributes][][question_answers_attributes][][numeric_value]", data: {autonumeric: {aSign: "#{sign_type}", vMin: '0', vMax: '9999999999', aPad: false, wEmpty: 'focus', pSign: "#{sign_placement}"}} %>
          <% elsif question.type === 'ChecklistQuestion' %>
            <% other_option = question.question_options.any?{|a| a.label == "Other"} ? "other-option" : ""  %>
            <div class="<%= question.id %> <%= other_option %>">
              <%= question_answer_fields.collection_check_boxes :option_id, question.question_options.order(:position), :id, :label, {},
                  {:name => "deal[question_responses_attributes][][question_answers_attributes][][option_id]" } do |option|
              %>
                <%
                  selected     = answers.select{ |a| (a.option_id == option.object.id) || (option.label == 'Other' && a.other_option_value.present?)}.first&.option_id.present?
                  answer_value = answers.first&.other_option_value
                %>
                  <div class="collection-check-box">
                    <div class="questionnaire-options">
                      <div class="questionnaire-check-box"><%= option.check_box({:checked => selected}) %></div>
                      <div class="questionnaire-label"><%= option.label %></div>
                    </div>
                  </div>
              <% end %>
            </div>
            <%
              other_option = question_response ? question_response.question_answers.select{ |a| a.other_option_value.present? }.first : nil
              value        = other_option ? other_option.other_option_value : nil
            %>
            <%= question_answer_fields.text_field :other_option_value, :value => value, :class => "form-control other-question #{question.id}", :name => "deal[question_responses_attributes][][question_answers_attributes][][other_option_value]" %>
          <% elsif question.type === 'DateQuestion' %>
            <%
              answer_overridden_value = answers.first&.date_value
              answer_value            = answer_overridden_value if answer_overridden_value.present?
              value                   = answer_value ? answer_value.strftime('%m/%d/%Y') : nil
            %>
            <%= question_answer_fields.text_field :date_value, :value => value, :class => "form-control datepicker", :placeholder => "Choose Date", :name => "deal[question_responses_attributes][][question_answers_attributes][][date_value]" %>
          <% else %>
            <%
              answer_overridden_value = answers.first&.text_value
              answer_value            = answer_overridden_value if answer_overridden_value.present?
            %>
            <%= question_answer_fields.text_field :text_value, :value => answer_value, :class => "form-control", :name => "deal[question_responses_attributes][][question_answers_attributes][][text_value]" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/app/counsel/questionnaires/_questionnaire_modal.html.erb
<%= render :layout => 'shared/modal', :locals => { :title => 'Questionnaire', :modal_class => 'large-modal' } do %>
  <%= render 'questionnaire_form' %>
<% end %>

app/views/app/counsel/questionnaires/edit.js.erb
App.Modal.show('<%= escape_javascript(render("questionnaire_modal")) %>')
App.Questionnaires.initialize()

app/views/app/counsel/questionnaires/new.js.erb
App.Modal.show('<%= escape_javascript(render("questionnaire_modal")) %>')
App.Questionnaires.initialize()