config/routes.rb
require 'routes/exceptions_app_constraint'
require 'routes/client_app_constraint'
require 'routes/counsel_app_constraint'
require 'routes/signer_app_constraint'

Doxly::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  concern :account_settings do
    get :my_profile, to: 'account_settings#my_profile'
    put :my_profile, to: 'account_settings#my_profile_save'
    get :integrations, to: 'account_settings#integrations'
    get :change_email, to: 'account_settings#change_email'
    post :change_email, to: 'account_settings#change_email_save'
    put :reconfirm_change_email, to: 'account_settings#reconfirm_change_email'
    put :cancel_change_email, to: 'account_settings#cancel_change_email'
    get :change_password, to: 'account_settings#change_password'
    put :change_password, to: 'account_settings#change_password_save'
    get :two_factor_authentication_settings, to: 'account_settings#two_factor_authentication_settings'
  end

  concern :entity_settings do
    get :entity_profile, to: 'entity_settings#entity_profile'
    post :entity_profile, to: 'entity_settings#entity_profile_save'
  end

  concern :starring do
    member do
      get :star
      get :unstar
    end
  end

  concern :documentable do
    get :mark_as_final
    get :undo_final
    get :view_document
  end

  concern :collection_refresh_list do
    get :refresh_list, :on => :collection
  end

  concern :working_group_intro do
    get :completed_working_group_intro, :on => :collection
    put :completed_working_group_intro, :on => :collection, to: 'roles#update_completed_working_group_intro'
  end

  concern :view_and_download do
    get :view, on: :member
    get :download, on: :member
  end

  def download_helpers(scope)
    get "/uploads/deals/:id/closing_books/:id/attachment/:filename",  :controller => "closing_books",  :action => "download_attachment", :constraints => {:filename => /.+(\/.+)*/ }, :as => "download_closing_book_attachment_as_#{scope}"
    get "/uploads/deals/:id/closing_books/:id/logo/:filename",  :controller => "closing_books",  :action => "download_closing_book_logo", :constraints => {:filename => /.+(\/.+)*/ }, :as => "download_closing_book_client_logo_as_#{scope}"
  end

  # For exception handling
  constraints ExceptionsAppConstraint do
    get '/404' => 'errors#render_not_found'
    get '/500' => 'errors#render_internal_server_error'
    get '*path' => 'errors#render_not_found'
  end

  get :register, to: 'registration#edit'
  put :register, to: 'registration#update'
  get :login_tokens, to: 'login_tokens#show'

  # For receiving the notifications from esignature providers
  post 'esignature_notifications' => 'esignature_notifications#index'

  match 'sso/adfs/federation_metadata(*path)' => 'sso#adfs_metadata', :via => :get

  constraints :subdomain => /^(?!api)(\w+)/ do
    scope :module => 'app' do
      devise_for :users, :path => '', :module => 'app/devise', :skip => [:passwords]
      devise_scope :user do
        post :forgot_password, :to => 'devise/passwords#create', :as => :user_password
        get :forgot_password, :to => 'devise/passwords#new', :as => :new_user_password
        get 'forgot_password/edit', :to => 'devise/passwords#edit', :as => :edit_user_password
        put :forgot_password, :to => 'devise/passwords#update'
        post 'auth/:saml/callback' => 'devise/omniauth_callbacks#success'
        get 'auth/:saml/setup' => 'devise/omniauth_callbacks#setup'

        unauthenticated do
          root to: 'devise/sessions#new'
        end
      end

      get :time_zone, to: 'time_zone#set'

      get :entity_switch, to: 'entity_switch#index'
      post :entity_switch, to: 'entity_switch#switch'

      get :refresh_api_auth, to: 'refresh_api_authentication#index'

      get "/uploads/user/:id/avatar",  :controller => "users",  :action => "show_avatar", :as => "show_user_avatar"

      resources :zendesk_sessions, only: [:index, :new]

      constraints CounselAppConstraint do
        scope :module => 'counsel' do
          get :docusign_settings, to: 'entity_settings#docusign_settings'
          post :docusign_settings, to: 'entity_settings#docusign_settings_save'
          get :licenses, to: 'entity_settings#licenses'
          concerns :account_settings, :entity_settings
          resources :net_documents_user_credentials, only: [] do
            get :authorize, on: :collection
          end
          resources :see_unity_imanage_user_credentials, only: [:create, :update]
          resources :imanage10_user_credentials, only: [:create, :update]
          resources :deals, :except => [:destroy, :show], :concerns => :collection_refresh_list do
            put :set_critical_errors_as_read
            resources :attachments do
              resources :versions, :concerns => :view_and_download
            end
            get :executed_versions
            get :export_tracker
            resources :closing_books do
              get :download_closing_book, :on => :member
              get :upload_cover_page, :on => :collection
              post :uploaded_cover_page, :on => :collection
              get :view_cover_page, :on => :collection
              get :show_cover_page, :on => :collection
              delete :remove_cover_page, :on => :collection
            end
            resources :questionnaires, :except => :destroy do
              post :save_responses, :on => :collection
            end
            get :voting_threshold
            resources :signature_groups do
              resources :block_collections, only: [] do
                resources :signature_entities, only: [] do
                  member do
                    get :include
                    get :exclude
                  end
                end
                resources :signing_capacities do
                  member do
                    get :include
                    get :exclude
                  end
                end
              end
              get  :import_from_working_group
              post :imported_from_working_group
            end
            resources :signature_pages, :concerns => :view_and_download do
              get :upload_custom_signature_page
              post :uploaded_custom_signature_page
              get :choose_from_document
              get :document_page_thumbnail
              get :view_document_page
              post :process_choose_from_document
              get :remove_custom_signature_page
              get :show_custom_signature_page
              get :edit_custom_signature_page
              get :signature_groups, :on => :collection
              get :show_signature_page, :on => :collection
              get :show_signature_page_entity, :on => :collection
              get :view_signature_page, :on => :collection
              get :download_thumbnail_sprite, on: :member
              get :download_custom_page_thumbnail, on: :member
              resources :signature_tabs, only: [:new, :create] do
                get :remove
              end
            end
            resources :signature_packets, :concerns => :view_and_download do
              get :display_signature_packet
              delete :void_signature_packet
              collection do
                get    :send_packets_confirm
                post   :send_packets
                get    :send_packet_wizard
                post   :send_packet
                get    :upload_manual_signatures
                post   :uploaded_manual_signatures
                get    :manage_signature_packets
                get    :view_signature_pages
                get    :send_reminder
                post   :remind_signer
                get    :set_default_signature_type_confirm
                get    :set_default_signature_type
                get    :cancel_set_default_signature_type
              end
            end
            resources :roles, concerns: :working_group_intro
            concerns :starring
            get :select_client, :on => :collection
            post :select_client_confirm, :on => :collection
            get :add_address, :on => :collection
            get :signature_page_settings

            resources :unmatched_signature_uploads do
              resources :unmatched_signature_upload_pages, concerns: :view_and_download
            end

            member do
              get :archive
              get :unarchive
              get :close
              get :reopen
            end

            resources :deal_entities, only: [:index, :new, :create, :destroy] do
              get :add_address, :on => :collection
              resources :deal_organization_users, except: [:index, :edit, :update, :show] do
                get :prepare_deal_invitation
                post :send_deal_invitation
              end
            end
            resources :deal_individual_users, only: [:index, :new, :create, :destroy] do
              get :prepare_deal_invitation
              post :send_deal_invitation
            end
            resources :categories do
              resources :tree_elements do
                get :edit_signature_page_footer
                get :edit_signature_page_header
                put :set_signature_page_header, :on => :member
                put :set_signature_page_footer, :on => :member
                get :set_signature_type
                get :set_show_footer, :on => :member
                get :set_show_header, :on => :member
                get :set_show_address, :on => :member
                get :set_show_date_signed, :on => :member
                put :update_multiple_pages, :on => :member
                get :render_redline_pdf
                resources :tree_element_signature_groups do
                  get :set_show_group_name, :on => :member
                end
                resources :attachments do
                  resources :versions, :concerns => :view_and_download do
                    get :sync_thumbnails

app/controllers/api/v1/entity_users_controller.rb
class Api::V1::EntityUsersController < Api::V1::ApplicationController
  include Controllers::Api::EntitySettings
  include Controllers::Api::EntityConnections
  
  api!
  def index
    check_read(:entity_user)
    entity_users = all_entity_users
    render_success(run_array_serializer(entity_users, EntityUserSerializer))
  end

  # api!
  # def new
  #   check_create(:entity_user)
  #   entity_user.build_user
  # end

   api!
  def show
    check_read(:entity_user)
    if entity
      scope         = entity.entity_users.includes(:all_deals => { :deal_entity_users => {:entity_user => :user }})
      entity_user   = scope.find(params[:id])
      active_deals  =  entity_user.all_deals.active.select{ |deal| deal.entities.include?(current_entity) }.group_by{ |d| 'Active Deals' }.sort
      render_success(user: entity_user.user, deals: active_deals )
    else
      render_unauthorized and return
    end
  end

  api!
  def create
    check_create(:entity_user)
    entity_user.assign_attributes(entity_user_params)
    user = User.find_by(email: params[:user][:email])
    # create new entity_user if user already exists
    if user
      new_entity_user = create_entity_user(user, entity_user.entity)
      
      # binding.pry
      render_success(new_entity_user) and return
    # create both new entity_user and a new user if user doesn't already exist
    else
      user, new_entity_user = save_entity_user_and_user(entity_user)
    end
    unless user.persisted? && new_entity_user.persisted?
      render_create_errors(user)
    else
      render_create_success
    end
  end

  # api!
  # def edit
  #   check_update(:entity_user) unless entity_user.id == current_entity_user.id
  #   check_read(:entity_user) if entity_user.id == current_entity_user.id
  #   render_unauthorized and return unless entity == current_entity || !entity_user.user.confirmed?
  # end

  api!
  def update
    check_update(:entity_user) unless entity_user.id == current_entity_user.id
    check_read(:entity_user) if entity_user.id == current_entity_user.id
    check_delete(:entity_user) if params[:user][:is_enabled]
    
    render_unauthorized and return unless entity == current_entity || !entity_user.user.confirmed?
    render_unauthorized and return if entity_user.id == current_entity_user.id && params[:user][:is_enabled].present?

    user                            = entity_user.user
    user.bypass_password_validation = true

    if !user.confirmed?
      if user.email != params[:user][:email] && params[:user][:email] != nil
        user.email = params[:user][:email]
        user.skip_reconfirmation!
      elsif user.email == nil
        user.bypass_email_validation = true
      end
    end
    user.assign_attributes(user_params)
    entity_user.title = params[:entity_user][:title]

    if user.valid? && entity_user.valid?
      user.save
      entity_user.save
      if entity == current_entity && params[:entity_user].present?
        entity_user.set_email_preference!(params[:entity_user][:email_digest_preference])
        entity_user.set_role!(params[:entity_user][:role], current_entity_user)
        entity_user.set_title!(params[:entity_user][:title])
      end
      render_success(entity_user)
      if is_current_entity
        # redirect_to entity_entity_user_path(entity, entity_user) and return
      else
        # respond_to_path(entities_path(:type => params[:type])) and return
      end
    else
      render_create_errors(user)
    end
  end

  api!
  def resend_invitation
    check_read(:entity_user)
    if entity_user.user.confirmation_token.present?
      entity_user.user.refresh_confirmation_token!
      #flash[:success] = "The invite has been resent"
      render_success({refresh_confirmation_token: entity_user.user.refresh_confirmation_token!})
      send_registration_invitation(entity_user.user, true)
    end
    # redirect_to :back
  end

  private

  def entity
    entity ||=  params[:entity_id].to_i == current_entity.id ? current_entity : current_entity.connected_entities.find_by(id: params[:entity_id])
  end

  def is_current_entity
    current_entity.id == entity.id
  end

  def all_entity_users
    current_entity.entity_users.joins(:user).includes(:user).order('first_name ASC')
  end

  # render errors
  def render_create_errors(user)
    user.errors.full_messages.each do |msg|
      # you can customize the error message here:
      entity_user.errors[:base] << msg
    end
    render_validation_failed(entity_user.errors.full_messages)
    # respond_to_turboboost('team_member_form', '.modal-body') and return
  end

  def render_create_success
    render_success(is_current_entity: is_current_entity, message: "User has been created successfully")
    # flash[:success] = "User has been created successfully"
    if is_current_entity

      # respond_to_path(entity_entity_users_path(current_entity)) and return
    else

      # respond_to_path(entities_path(:type => params[:type])) and return
    end
  end
  
end

app/controllers/app/counsel/account_settings_controller.rb
class App::Counsel::AccountSettingsController < App::ApplicationController
  include Controllers::AccountSettings

  def integrations
    check_create(:entity_level_dms_integration)
  end
end

app/controllers/app/counsel/attachments_controller.rb
class App::Counsel::AttachmentsController < App::ApplicationController
  include Controllers::Attachments
end

app/controllers/app/counsel/categories_controller.rb
class App::Counsel::CategoriesController < App::ApplicationController
  include Controllers::Categories

  layout "deals"
end

app/controllers/app/counsel/entity_connections_controller.rb
class App::Counsel::EntityConnectionsController < App::ApplicationController
  include Controllers::EntityConnections

  def new
    check_create(:entity_connection)
    @entities = []
    entity
  end

  def edit
    check_update(:entity_connection)
    entity_connection
    entity
  end

  def create
    check_create(:entity_connection)
    @entity = Entity.find(params[:entity_id]) if params[:entity_id]
    if save_entity_connections_and_entities(entity, entity_connection)
      entity.build_primary_address(primary_address_params).save
      if entity_connection.is_pending
        flash.now[:success] = "Connection Request Sent"
        @class = "new-party"
      else
        flash.now[:success] = "Connection Created"
        @class = "new-law-firm"
      end
    else
      @errors = "people_page"
      @deal = current_entity_user.all_deals.find(params[:deal_id]) if params[:deal_id]
      @search_term = params[:entity][:name]
      @entities = FuzzyMatch.new(Entity.all, :read => :name, find_all_with_score: true, threshold: 0.5).find(@search_term).select{|org| org.last > 0.5}.take(5).map{|org| org.first} - [current_entity]
      render 'create_errors' and return
    end
  end

  def resend_connection_invitation
    check_read(:entity_connection)
    entity_connection = current_entity.entity_connections.find(params[:entity_connection_id])
    InvitationMailer.entity_connection_invitation_email(entity_connection).deliver_later
    flash.now[:success] = "Invitation Successfully Re-sent"
    render "shared/blank"
  end


  def update
    check_update(:entity_connection)
    entity_connection
    entity
    entity.assign_attributes(entity_params)
    if entity.valid?
      entity.save
      flash[:success] = "#{entity_type_text} has been updated successfully"
      respond_to_path(entities_path(:type => params[:type])) and return
    else
      render :edit and return
    end
  end

  def add_address
    check_update(:entity)
    @search_term = params[:search_term]
    entity
  end

  protected

  def entity
    @entity ||= entity_connection.new_record? ? entity_connection.build_connected_entity : entity_connection.connected_entity
  end

  def entity_type_text
    params[:type] == "law_firm" ? "Law Firm" : "Party"
  end

end

app/views/app/counsel/entity_users/_edit_team_member_form.html.erb
<%= render "app/shared/errors", :errors => @entity_user.user.errors.full_messages %>
<%= form_for @entity_user.user, :url => entity_entity_user_path(@entity_user.entity, @entity_user, :type => params[:type]), :method => :put, :html => { :multipart => true } do |f| %>
  <%= render "app/shared/change_settings_form", :form => f, :cancel_path => "App.Helpers.navigateTo('#{entity_entity_users_path(@entity_user.entity)}')", :entity_user => @entity_user %>
<% end %>

app/views/app/counsel/entity_users/_team_member_form.html.erb
<%
  path = unless current_entity.id == @entity.id
    @entity_user.new_record? ? entity_entity_users_path(@entity, :type => params[:type]) : entity_entity_user_path(@entity, @entity_user, :type => params[:type])
  else
    entity_entity_users_path(@entity, :type => params[:type])
  end
  method = @entity_user.new_record? ? :post : :put
%>

<%= render "app/shared/errors", :errors => @entity_user.errors.full_messages %>
<%= form_for @entity_user.user, :url => path, :method => method do |f| %>
  <%= render 'shared/people/team_member_form_fields', :form => f %>
<% end %>

app/views/app/counsel/entity_users/_team_member_modal.html.erb
<%
  title = ''
  unless current_entity.id == @entity.id
    title = "#{@entity.name} - "
    title += 'Add ' if @entity_user.new_record?
  end
  title += @entity_user.new_record? ? 'New Team Member' : 'Edit Team Member'
%>
<%= render :layout => 'shared/modal', :locals => { :title => title } do %>
  <%= render 'entity_users/team_member_form' %>
<% end %>

app/views/app/counsel/entity_users/_team_members_list.html.erb
<div class="team-list">
  <% @entity_users.each do |entity_user| %>
    <% user = entity_user.user %>
    <div class="team-list-item">
      <div class="team">
        <%= render 'app/shared/user', user: user, subtitle: user.email, entity_user: entity_user %>
      </div>
      <div class="stat">
        <div class="team-stat-item">
          <b><%= entity_user.all_deals.active.count %></b> Active Deals
        </div>
        <div class="team-stat-item">
          <b><%= entity_user.all_deals.complete.count %></b> Complete Deals
        </div>
      </div>
      <div class="actions">
        <%= link_to '', resend_invitation_entity_entity_user_path(entity_user.entity, entity_user), :class => "fa fa-envelope-o" unless entity_user.user.confirmed? %>
        <%= link_to '', entity_entity_user_path(entity_user.entity, entity_user), :class => "fa fa-gear" %>
      </div>
    </div>
  <% end %>
  <% if @entity_users.size == 0 %>
    <div className="no-results">
      <div className="header">There aren't any team members to show.</div>
    </div>
  <% end %>
</div>

app/views/app/counsel/entity_users/edit.html.erb
<% top_view = current_entity.is_counsel ? "shared/top_counsel" : "shared/top_client" %>
<%= render top_view, title: "Team / #{@entity_user.name}" %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content-single">
        <div class="panel panel-team-description">
          <div class="inner">
            <%= render 'app/shared/user', user: @entity_user.user, subtitle: @entity_user.user.email, entity_user: @entity_user %>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        Edit Team Member
      </div>
      <div class="panel-body" id="edit-team-member-form">
        <%= render 'edit_team_member_form' %>
      </div>
    </div>
  </div>
</div>

app/views/app/counsel/entity_users/edit.js.erb
App.Modal.show('<%= escape_javascript(render("team_member_modal")) %>')

app/views/app/counsel/entity_users/index.html.erb
<%= render "shared/top_navs/index", title: 'People' %>

<%= render 'frontend/index' %>
  <script>
    $(function() {
      App.React.EntityUsersController.renderPeople(<%= params[:required] %>)
    })
  </script>

app/views/app/counsel/entity_users/new.js.erb
App.Modal.show('<%= escape_javascript(render("team_member_modal")) %>')
App.Forms.appendRoleDescription()

app/views/app/counsel/entity_users/refresh_list.js.erb
$('#team-members-list').html('<%= escape_javascript(render("team_members_list")) %>')
App.Helpers.initialize()

app/views/app/counsel/entity_users/show.html.erb
<%
  deals               = @entity_user.all_deals
  # dangerous line of code -- do not change without checking with other team members
  active_deals        = deals.active.select{ |deal| deal.entities.include?(current_entity) }.group_by{ |d| 'Active Deals' }.sort
  active_deals        = {"Active Deals" => []} if active_deals.blank?
  # dangerous code -- do not change without checking with other team members
  completed_deals     = deals.complete.select{ |deal| deal.entities.include?(current_entity) }.group_by{ |d| 'Completed Deals' }.sort
  completed_deals     = {"Completed Deals" => []} if completed_deals.blank?
  top_view            = current_entity.is_counsel ? "shared/top_counsel" : "shared/top_client"
  entity              = @entity_user.entity
%>
<%= render top_view, title: "People / #{entity.is_a?(Individual) ? 'Individual' : entity.name} / #{@entity_user.name}" %>
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="content-single">
        <div class="panel panel-list">
          <div class="inner">
            <div class="team-list-item">
              <div class="team">
                <%= render 'app/shared/user', user: @entity_user.user, subtitle: @entity_user.user.email, entity_user: @entity_user %>
              </div>
              <div class="stat">
                <div class="team-stat-item">
                  <%=h @entity_user.user.full_address.html_safe %>
                  <%=h "Phone: #{number_to_phone(@entity_user.user.phone, area_code: true)}<br>".html_safe if @entity_user.user.phone.present? %>
                  <%= "Fax: #{number_to_phone(@entity_user.user.fax, area_code: true)}" if @entity_user.user.fax.present? %>
                </div>
              </div>
              <div class="actions">
                <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_entity_entity_user_path(@entity_user.entity, @entity_user) if @entity_user.entity == current_entity %>
                <%= link_to '<i class="fa fa-envelope-o"></i>'.html_safe, resend_invitation_entity_entity_user_path(@entity_user.entity, @entity_user), :class => "btn-edit" unless @entity_user.user.confirmed? %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="content-single">
        <%= render 'shared/deals/deals_list', :deals => active_deals %>
        <%= render 'shared/deals/deals_list', :deals => completed_deals %>
      </div>
    </div>
  </div>
</div>